# Generated by Django 2.1.12 on 2019-09-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date_time', models.DateTimeField()),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('phone_number', models.CharField(max_length=64)),
                ('occupation', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('organization', models.CharField(max_length=256)),
                ('invitation_required', models.BooleanField()),
                ('checked_in', models.BooleanField(default=False)),
            ],
        ),
    ]
