# Generated by Django 2.1.12 on 2019-09-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='checked_in',
            new_name='is_checked_in',
        ),
        migrations.AddField(
            model_name='participant',
            name='check_in_time',
            field=models.TimeField(null=True, verbose_name='check-in time'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registration_date_time',
            field=models.DateTimeField(verbose_name='date and time of registration'),
        ),
    ]
